[2024-09-25T19:54:59.315+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-25T19:54:59.327+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape manual__2024-09-25T19:54:58.348423+00:00 [queued]>
[2024-09-25T19:54:59.331+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AirCrashInvestigation_pipeline.scrape manual__2024-09-25T19:54:58.348423+00:00 [queued]>
[2024-09-25T19:54:59.332+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-09-25T19:54:59.339+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): scrape> on 2024-09-25 19:54:58.348423+00:00
[2024-09-25T19:54:59.342+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=308) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-25T19:54:59.342+0000] {standard_task_runner.py:63} INFO - Started process 309 to run task
[2024-09-25T19:54:59.343+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'AirCrashInvestigation_pipeline', 'scrape', 'manual__2024-09-25T19:54:58.348423+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp5b0x3or4']
[2024-09-25T19:54:59.344+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask scrape
[2024-09-25T19:54:59.369+0000] {task_command.py:426} INFO - Running <TaskInstance: AirCrashInvestigation_pipeline.scrape manual__2024-09-25T19:54:58.348423+00:00 [running]> on host a5905166bf2e
[2024-09-25T19:54:59.406+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='AirCrashInvestigation_pipeline' AIRFLOW_CTX_TASK_ID='scrape' AIRFLOW_CTX_EXECUTION_DATE='2024-09-25T19:54:58.348423+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-25T19:54:58.348423+00:00'
[2024-09-25T19:54:59.406+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-25T19:54:59.412+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-25T19:54:59.413+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/tasks/flightDataWebScrape.py']
[2024-09-25T19:54:59.417+0000] {subprocess.py:86} INFO - Output:
[2024-09-25T19:58:15.891+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to removed. Terminating instance.
[2024-09-25T19:58:15.892+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-09-25T19:58:15.893+0000] {process_utils.py:132} INFO - Sending 15 to group 309. PIDs of all processes in the group: [310, 309]
[2024-09-25T19:58:15.894+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 309
[2024-09-25T19:58:15.895+0000] {taskinstance.py:2607} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-09-25T19:58:15.895+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2024-09-25T19:58:15.897+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-25T19:58:15.927+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=309, status='terminated', exitcode=0, started='19:54:58') (309) terminated with exit code 0
[2024-09-25T19:58:15.928+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=310, status='terminated', started='19:54:58') (310) terminated with exit code None
